workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-npm

pipeline:
  deps:
    image: golang:1.10
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
