branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    username:${name}
    commands:
      - pip install -U sphinx
      - git config --global user.name "shrinilthakkar"
      - git config --global user.email "shrinil@moengage.com"
      - export GITHUB_TOKEN="5137b5701cb467277933ae5a5c21a1e8bc6ffc90"
      - git branch -D merged_state || true
      - git checkout -b merged_state
      - cd sphinx
      - sphinx-build -b html ./rst/ ./html/
      - git status
      - git add html
      - git status
      - git commit -am "html added"
      - git status
      - cd ./../
      #- cat .git/config
      #- echo ${name}
      #- curl -I http://drone.moengage.com/api/repos/shrinilthakkar/shrinilthakkar/secrets
      #- git push origin merged_state
      #- drone secrets ls <shrinilthakkar>
  
  publish:
    image: plugins/docker
      - drone secret add --image plugins/docker DOCKER_USERNAME octocat

