branches: [master]
pipeline:
  build:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pip install nose
      - pip install coverage
      - pylint *.py
      - pylint --generate-rcfile > .pylintrc
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
