branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    commands:
      - pip install -U sphinx
      - git config --global user.name "shrinilthakkar"
      - git config --global user.email "shrinil@moengage.com"
      - git branch -D merged_state || true
      - git checkout -b merged_state
      - cd sphinx
      - pwd
      - sphinx-build -b html ./rst/ ./html/
      - git push origin merged_state
