branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    commands:
      - pip install -U sphinx
      - git config --global user.name "shrinilthakkar"
      - git config --global user.email "shrinil@moengage.com"
      - export GITHUB_TOKEN="dc8bfae015b4510a75e40c730931f1418bc6ff82"
      - git branch -D merged_state || true
      - git checkout -b merged_state
      #- git checkout --orphan gh-pages
      - cd sphinx
      - sphinx-build -b html ./rst/ ./html/
      - cat ./html/hello.html
      - git status
      - git add html
      - git commit -am "html added"
      - git push https://shrinilthakkar:a0946c7c3de86820efdd9623dc30781d13396781@github.com/shrinilthakkar/shrinilthakkar.git/ merged_state
      - cd ./../
      #- cat .git/config
      #- echo ${name}
      #- curl -I http://drone.moengage.com/api/repos/shrinilthakkar/shrinilthakkar/secrets
      #- git push origin merged_state
      #- drone secrets ls <shrinilthakkar>
  
  publish:
    image: plugins/docker
    repo: shrinilthakkar/shrinilthakkar
    secrets: [ docker_username , docker_password ]

