branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    commands:
      - pip install -U sphinx
      - git config --global user.name "shrinilthakkar"
      - git config --global user.email "shrinil@moengage.com"
      - export GITHUB_TOKEN=5137b5701cb467277933ae5a5c21a1e8bc6ffc90
      - git branch -D merged_state || true
      - git checkout -b merged_state
      - cd sphinx
      - pwd
      - sphinx-build -b html ./rst/ ./html/
      - git status
      - git add html
      - git status
      - git commit -am "html added"
      - git status
      - cd ./../
      - cat .git/config
      - echo $name
      - curl -I http://drone.moengage.com/api/repos/shrinilthakkar/shrinilthakkar/secrets
      
  git_push:
    image: appleboy/drone-git-push
    remote_name: origin
    branch: merged_state
    local_ref: merged_state
