branches: [master]
pipeline:
  install:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pip install nose
      - pip install coverage
      - pip install -U sphinx
  test:
    image: python:2.7
    commands:
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
