branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    commands:
      - pip install -U sphinx
      - git config --global user.name "shrinilthakkar"
      - git config --global user.email "shrinil@moengage.com"
      - git branch -D merged_state || true
      - git checkout -b merged_state
      # - git checkout --orphan gh-pages
      - cd sphinx-local
      - make clean
      - make html
      - cat ./html/hello.html
      - sphinx-build -b html ./rst/ ./html/
      - cat ./html/hello.html
      - cat ./_build/html/genindex.html
      - git add html
      - git commit -am "html added"
      #- drone secrets add shrinilthakkar/shrinilthakkar KEY bcbff33fd3183109e280b38ab645e7e83c58e853
      #- git push https://shrinilthakkar:KEY@github.com/shrinilthakkar/shrinilthakkar.git/ merged_state
      - cd ./../
      #- cat .git/config
      #- curl -I http://drone.moengage.com/api/repos/shrinilthakkar/shrinilthakkar/secrets
      #- git push origin merged_state
      #- drone secrets ls <shrinilthakkar>
