branches: [master]
pipeline:

  syntax_check:
    image: python:2.7
    commands:
      - python -m pip install pylint
      - pylint --generate-rcfile > .pylintrc
      - pylint *.py
      
  test:
    image: python:2.7
    commands:
      - pip install nose
      - pip install coverage
      - nosetests ./tests/ --with-coverage --cover-html --cover-tests
      
  documentation:
    image: python:2.7
    commands:
      - pip install -U sphinx
      - sphinx-apidoc -o shrinilthakkar/shrinilthakkar/sphinx/rst/ shrinilthakkar/shrinilthakkar/sphinx/scripts/
      - sphinx-build -b html shrinilthakkar/shrinilthakkar/sphinx/rst/ shrinilthakkar/shrinilthakkar/sphinx/html/
