language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=where.the.testing.configuration.lies
install:
  - pip install -U sphinx
  - cd sphinx
  - sphinx-build -b html ./rst/ ./html/
  - cat ./html/hello.html
