branches:
  only:
    - master
language: python
python:
  - "2.7"
install:
  - pip install -U sphinx
  - git branch -D merged_state || true
  - git checkout -b merged_state
  - cd sphinx
  - rm -rf ./html/*
  - sphinx-build -b html ./rst/ ./html/
  - git config --global user.name "shrinilthakkar"
  - git config --global user.email "shrinil@moengage.com"
  - cat ../.git/config
  - git status
  - git add html
  - git commit -am "adding html files"
  - echo $key
  - git push https://shrinilthakkar:$key@github.com/shrinilthakkar/shrinilthakkar.git/
