branches:
  only:
    - master
language: python
python:
  - "2.7"

install:
  - python -m pip install pylint
  - pylint --generate-rcfile > .pylintrc
  - pylint *.py

before_script:
  - pip install nose
  - pip install coverage
  - nosetests ./tests/ --with-coverage --cover-html --cover-tests
  
script:
  - pip install -U sphinx
  - git branch -D merged_state || true
  - git push -D https://shrinilthakkar:$key@github.com/shrinilthakkar/shrinilthakkar.git/ merged_state || true
  - git checkout -b merged_state
  - cd sphinx-local
  - sphinx-apidoc -o ./rst/ ./scripts/
  - sphinx-build -b html ./rst/ ./html/
  - git config --global user.name "shrinilthakkar"
  - git config --global user.email "shrinil@moengage.com"
  - git add html
  - git commit -am "adding html files"
  - git push -u https://shrinilthakkar:$key@github.com/shrinilthakkar/shrinilthakkar.git/ merged_state
